### ISSUE TITLE
Message not found

### ISSUE THREAD

**Issue by Teteros** [jecrell/GithubBot#1]
Hi, I've been trying to get this to run on my own discord but wasn't very succesful.
What I did so far:

1. Clone repo
2. Rename auth files and add tokens to `auth.json` and `authGithub.json`
3. Fix case sensitive import in bot.js (linux)
```diff
-const Bot = require('./models/Bot')
+const Bot = require('./models/bot')
```
4. Replace repos in `db/repos.json` to my projects'.
5. npm install && node bot.js

Then `!issues` (e.g `!issues repo` or `!issues repo issuetitle | msgbody`
commands fail:

```
Bot startup...
Loading message function...
Start took: 618MS
Shard #0 active with 1 guilds
(node:14343) UnhandledPromiseRejectionWarning: HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/#list-issues-for-a-repository"}
    at response.text.then.message (/tmp/GithubBot/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:14343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas? I've tried the command above on a private repo, maybe those aren't supported.

**Comment by Teteros** [comment]
>I've tried the command above on a **private repo**, maybe those aren't supported.

Yeah, this was it. Authenticating to Octokit first returns the request successfully.
As simple as

```js
        //Authenticate to Octokit
        octokit.authenticate({
          type: 'oauth',
          token: authGithub.token
        })
```

before

```js
//Get repository data from Octokit
        octokit.issues.getForRepo({
```
in commands/issues.js and it's fixed!
